name: "Record deployment"
description: "Record a deployment done externally to Prodvana."
inputs:
  app:
    description: "A unique name for the application being deployed. An application is a collection of related services with the same set of release channels. e.g. infra, product, <company name>"
    required: true
  service:
    description: "A unique name for the service being deployed, e.g. api, web"
    required: true
  release_channel:
    description: "A unique name for the release channel of the service being deployed, e.g. staging, prod"
    required: true
  deployment_system:
    description: "The deployment system doing the deployment"
    required: true
    default: "github-actions"
  pending:
    description: "Record the deployment in pending state instead of succeeded state, meant to be used with update-deployment-status action"
    type: boolean
    defualt: false
  auth_context:
    description: "pvnctl auth context to use. If you're using this Action with init-pvnctl, leave as the default"
    required: true
    default: "default"
outputs:
  deployment_id:
    description: "A unique identifier for the deployment created"
    value: ${{ steps.pvnctl-deployments-record.outputs.deployment-id }}
  release_id:
    description: "same as deployment_id, preserved for backwards compatibility"
    value: ${{ steps.pvnctl-deployments-record.outputs.release-id }}
runs:
  using: "composite"
  steps:
    - name: pvnctl deployment record
      id: pvnctl-deployments-record
      shell: bash
      run: |
        set -euxo pipefail
        pvnctl auth context use ${{ inputs.auth_context }}
        CMD="pvnctl releases record --app=${{ inputs.app }} --service=${{ inputs.service }} --release-channel=${{ inputs.release_channel }} --deployment-system=${{ inputs.deployment_system }}"
        if [[ "${{ inputs.pending }}" == "true" ]]; then
          CMD="$CMD --pending"
        fi
        DEPLOYMENT_ID=$(eval "${CMD}")
        echo "release-id=$DEPLOYMENT_ID" >> $GITHUB_OUTPUT
        echo "deployment-id=$DEPLOYMENT_ID" >> $GITHUB_OUTPUT
